# Generated by Django 5.0.2 on 2024-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Car/media/uploades/'),
        ),
    ]
