# Generated by Django 5.0.2 on 2024-07-04 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy_Car', '0001_initial'),
        ('Car', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases1', to='Car.car'),
        ),
    ]
